"""empty message

Revision ID: 3bc18584bdba
Revises: 28e7907742b7
Create Date: 2022-09-02 19:31:22.286681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc18584bdba'
down_revision = '28e7907742b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorites', ['id'])
    op.create_unique_constraint(None, 'ingredient', ['id'])
    op.create_unique_constraint(None, 'meal', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'weekly_plan', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_plan', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'meal', type_='unique')
    op.drop_constraint(None, 'ingredient', type_='unique')
    op.drop_constraint(None, 'favorites', type_='unique')
    # ### end Alembic commands ###
