"""empty message

Revision ID: b4dafc42594e
Revises: 
Create Date: 2022-09-12 19:15:04.446063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dafc42594e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.String(length=120), nullable=False),
    sa.Column('lunch', sa.String(length=120), nullable=False),
    sa.Column('dinner', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breakfast'),
    sa.UniqueConstraint('dinner'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('lunch')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sumarize', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nutrients', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sumarize', sa.String(length=120), nullable=False),
    sa.Column('nutrients', sa.String(length=80), nullable=False),
    sa.Column('ingredients', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weekly_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.String(length=120), nullable=False),
    sa.Column('tuesday', sa.String(length=120), nullable=False),
    sa.Column('wednesday', sa.String(length=120), nullable=False),
    sa.Column('thursday', sa.String(length=120), nullable=False),
    sa.Column('friday', sa.String(length=120), nullable=False),
    sa.Column('saturday', sa.String(length=120), nullable=False),
    sa.Column('sunday', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friday'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('monday'),
    sa.UniqueConstraint('saturday'),
    sa.UniqueConstraint('sunday'),
    sa.UniqueConstraint('thursday'),
    sa.UniqueConstraint('tuesday'),
    sa.UniqueConstraint('wednesday')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meals_id', sa.Integer(), nullable=True),
    sa.Column('foods_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foods_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['meals_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('weekly_plan')
    op.drop_table('user')
    op.drop_table('meal')
    op.drop_table('food')
    op.drop_table('daily_plan')
    # ### end Alembic commands ###
