"""empty message

Revision ID: b5f47f60478f
Revises: 63f63f79f383
Create Date: 2022-09-14 20:10:19.980155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f47f60478f'
down_revision = '63f63f79f383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.drop_column('meal', 'user_id')
    # ### end Alembic commands ###
