"""empty message

Revision ID: fa7d445ea7af
Revises: 3bc18584bdba
Create Date: 2022-09-12 16:41:35.859857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7d445ea7af'
down_revision = '3bc18584bdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('breakfast', sa.String(length=120), nullable=False),
    sa.Column('lunch', sa.String(length=120), nullable=False),
    sa.Column('dinner', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breakfast'),
    sa.UniqueConstraint('dinner'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('lunch')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sumarize', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nutrients', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('ingredients')
    op.drop_table('ingredient')
    op.add_column('favorites', sa.Column('foods_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'food', ['foods_id'], ['id'])
    op.add_column('meal', sa.Column('sumarize', sa.String(length=120), nullable=False))
    op.add_column('meal', sa.Column('nutrients', sa.String(length=80), nullable=False))
    op.add_column('meal', sa.Column('ingredients', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('meal', 'ingredients')
    op.drop_column('meal', 'nutrients')
    op.drop_column('meal', 'sumarize')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'foods_id')
    op.create_table('ingredient',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ingredient_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nutrients', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ingredient_pkey'),
    sa.UniqueConstraint('id', name='ingredient_id_key'),
    sa.UniqueConstraint('name', name='ingredient_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ingredients',
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name='ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], name='ingredients_meal_id_fkey'),
    sa.PrimaryKeyConstraint('ingredient_id', 'meal_id', name='ingredients_pkey')
    )
    op.drop_table('food')
    op.drop_table('daily_plan')
    # ### end Alembic commands ###
