"""empty message

Revision ID: ff9ee75d5218
Revises: b5f47f60478f
Create Date: 2022-09-14 20:15:48.778027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9ee75d5218'
down_revision = 'b5f47f60478f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_plan', 'dinner')
    op.drop_column('daily_plan', 'breakfast')
    op.drop_column('daily_plan', 'lunch')
    op.add_column('meal', sa.Column('daily_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meal', 'daily_plan', ['daily_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.drop_column('meal', 'daily_plan_id')
    op.add_column('daily_plan', sa.Column('lunch', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('daily_plan', sa.Column('breakfast', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('daily_plan', sa.Column('dinner', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
